### ISSUE TITLE
Flatbuffers Dumper

### ISSUE THREAD

**Issue by ghost** [aardappel/aarded#1]
Hi Aardappel, I know you ha e though about this before but did you even make a dumper for Flatbuffers, I know it wouldn’t be exact especially around vector tables but it would still be extremely useful as most people will be switching to Flatbuffers from protobuf

**Comment by aardappel** [comment]
Can you re-open this question here: https://github.com/google/flatbuffers/issues
The current repo is unrelated to FlatBuffers.
